using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyAI : MonoBehaviour
{
    [SerializeField] protected GameObject _player;
    protected FieldOfView fov;

    public Transform playerLastKnownPos;

    SFX sfxClass;

    private void Start()
    {
        fov = GetComponent<FieldOfView>();
        _player = GameObject.FindGameObjectWithTag("Player");
        sfxClass = FindObjectOfType<SFX>();
    }
    public bool IsPlayerInRange()
    {
        if (_player == null) return false;
        if (fov.visibleTargets.Contains(_player.transform))
        {
            return true;
        }
        return false;
    }

    private void Update()
    {
        if (IsPlayerInRange())
        {
            Debug.Log("IMMA GETCHYA");
            
        }
        if (!IsPlayerInRange())
        {
            //Debug.Log("I LOST YA");
        }
    }
}

/*public class Example : MonoBehaviour
{
    // Adjust the speed for the application.
    public float speed = 1.0f;

    // The target (cylinder) position.
    private Transform target;

    void Awake()
    {
        // Position the cube at the origin.
        transform.position = new Vector3(0.0f, 0.0f, 0.0f);

        // Create and position the cylinder. Reduce the size.
        var cylinder = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        cylinder.transform.localScale = new Vector3(0.15f, 1.0f, 0.15f);

        // Grab cylinder values and place on the target.
        target = cylinder.transform;
        target.transform.position = new Vector3(0.8f, 0.0f, 0.8f);

        // Position the camera.
        Camera.main.transform.position = new Vector3(0.85f, 1.0f, -3.0f);
        Camera.main.transform.localEulerAngles = new Vector3(15.0f, -20.0f, -0.5f);

        // Create and position the floor.
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Plane);
        floor.transform.position = new Vector3(0.0f, -1.0f, 0.0f);
    }

    void Update()
    {
        // Move our position a step closer to the target.
        var step = speed * Time.deltaTime; // calculate distance to move
        transform.position = Vector3.MoveTowards(transform.position, target.position, step);

        // Check if the position of the cube and sphere are approximately equal.
        if (Vector3.Distance(transform.position, target.position) < 0.001f)
        {
            // Swap the position of the cylinder.
            target.position *= -1.0f;
        }
    }
}*/
